# Generated by Django 5.2 on 2025-09-11 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manicuristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('tardanza', 'Tardanza'), ('ausente', 'Ausente'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('horario', 'Horario'), ('anulada', 'Anulada')], default='normal', max_length=20)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, choices=[('apertura', 'Apertura (10:00 - 19:00)'), ('cierre', 'Cierre (11:00 - 20:00)')], max_length=20, null=True)),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to='incapacidades/')),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_ausencia', models.CharField(blank=True, choices=[('completa', 'Día Completo'), ('por_horas', 'Por Horas')], max_length=20, null=True)),
                ('hora_inicio_ausencia', models.TimeField(blank=True, null=True)),
                ('hora_fin_ausencia', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='manicuristas.manicurista')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha', 'manicurista__nombre'],
                'unique_together': {('manicurista', 'fecha')},
            },
        ),
    ]
