# Generated by Django 5.2 on 2025-09-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprahasinsumos', '0001_initial'),
        ('compras', '0001_initial'),
        ('insumos', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprahasinsumo',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='comprahasinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo'),
        ),
    ]
