# Generated by Django 5.2 on 2025-09-11 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='accion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.accion'),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.modulo'),
        ),
    ]
