# Generated by Django 5.2 on 2025-09-11 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manicurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la manicurista', max_length=200)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte')], max_length=2, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('especialidad', models.CharField(blank=True, choices=[('Manicure Clásica', 'Manicure Clásica'), ('Manicure Francesa', 'Manicure Francesa'), ('Manicure Gel', 'Manicure Gel'), ('Manicure Acrílica', 'Manicure Acrílica'), ('Nail Art', 'Nail Art'), ('Pedicure', 'Pedicure'), ('Uñas Esculpidas', 'Uñas Esculpidas'), ('Decoración de Uñas', 'Decoración de Uñas'), ('Manicure Express', 'Manicure Express'), ('Tratamientos de Cutículas', 'Tratamientos de Cutículas')], help_text='Especialidad principal de la manicurista', max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="El número de celular debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contraseña_temporal', models.CharField(blank=True, max_length=128, null=True)),
                ('debe_cambiar_contraseña', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
