# Generated by Django 5.2 on 2025-09-11 04:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor base de la liquidación', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonificacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonificación adicional', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'db_table': 'liquidaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
