# Generated by Django 5.2 on 2025-09-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liquidaciones', '0001_initial'),
        ('manicuristas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='manicurista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='manicuristas.manicurista'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacion',
            unique_together={('manicurista', 'fecha_inicio', 'fecha_final')},
        ),
    ]
