# Generated by Django 5.2 on 2025-09-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(blank=True, help_text='Correo electrónico del usuario', max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('codigo', models.CharField(help_text='Código de 6 dígitos para recuperación', max_length=6, verbose_name='Código')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('expiracion', models.DateTimeField(help_text='Fecha y hora de expiración del código', verbose_name='Expiración')),
                ('usado', models.BooleanField(default=False, help_text='Indica si el código ya fue utilizado', verbose_name='Usado')),
            ],
            options={
                'verbose_name': 'Código de Recuperación',
                'verbose_name_plural': 'Códigos de Recuperación',
                'ordering': ['-creado_en'],
            },
        ),
    ]
