# Generated by Django 5.2 on 2025-09-11 04:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abastecimientos', '0001_initial'),
        ('insumos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoHasAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='abastecimientos.abastecimiento')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Insumo - Abastecimiento',
                'verbose_name_plural': 'Insumos - Abastecimientos',
            },
        ),
    ]
