# Generated by Django 5.2 on 2025-09-11 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_cita', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la cita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('cancelada_por_novedad', 'Cancelada por Novedad')], default='pendiente', max_length=30, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación')),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, help_text='Precio total de todos los servicios', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio total de la cita')),
                ('precio_servicio', models.DecimalField(decimal_places=2, help_text='Precio del servicio principal (para compatibilidad)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del servicio principal')),
                ('duracion_total', models.PositiveIntegerField(default=0, help_text='Duración total de todos los servicios en minutos', verbose_name='Duración total (minutos)')),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración del servicio principal (para compatibilidad)', verbose_name='Duración estimada (minutos)')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_cita', '-hora_cita'],
            },
        ),
    ]
