# Generated by Django 5.2 on 2025-09-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('manicuristas', '0001_initial'),
        ('novedades', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='manicurista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manicuristas.manicurista', verbose_name='Manicurista'),
        ),
        migrations.AddField(
            model_name='cita',
            name='novedad_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_afectadas', to='novedades.novedad', verbose_name='Novedad Relacionada'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(help_text='Servicio principal (para compatibilidad)', on_delete=django.db.models.deletion.CASCADE, related_name='citas_principal', to='servicios.servicio', verbose_name='Servicio Principal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(blank=True, help_text='Servicios incluidos en la cita', to='servicios.servicio', verbose_name='Servicios'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('manicurista', 'fecha_cita', 'hora_cita')},
        ),
    ]
